name: SDK:main <-> Databroker:master

on:
  schedule:
      - cron: "0 0 * * *"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Run Tests
        uses: ./.github/actions/run-tests
        with:
          upload-test-reports: true
          databroker-version: master
          kotest-tag: "Integration"
